# Read the Docs configuration file for YouTrack CLI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# This configuration is designed to work with ReadTheDocs build automation
# that triggers only on version tags (configured in ReadTheDocs admin interface)

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

# Additional output formats for releases
formats:
  - pdf
  - epub
